ALTER SEQUENCE seq_codigo_transaccion_ws RESTART;
ALTER SEQUENCE seq_datos_lotes_i dRESTART;
ALTER SEQUENCE seq_datos_sucursales_id RESTART;
ALTER SEQUENCE seq_log_email_envios_envio_id RESTART;
ALTER SEQUENCE seq_datos_almacenes_id RESTART;
ALTER SEQUENCE seq_datos_marcas_id RESTART;
ALTER SEQUENCE seq_datos_tablas_id RESTART;
ALTER SEQUENCE seq_mensajeria_anmat_mensajeria_id RESTART;
ALTER SEQUENCE seq_datos_autogestion_autogestion_id RESTART;
ALTER SEQUENCE seq_datos_medicos_id RESTART;
ALTER SEQUENCE seq_datos_trazabilidad_traza_id RESTART;
ALTER SEQUENCE seq_movimientos_trazabilidad_id_movimiento RESTART;
ALTER SEQUENCE seq_datos_categorias_id RESTART;
ALTER SEQUENCE seq_datos_movimientos_id_mov RESTART;
ALTER SEQUENCE seq_datos_usuarios_id RESTART;
ALTER SEQUENCE seq_tipos_movimientos_trazas_tipo_mov_id RESTART;
ALTER SEQUENCE seq_datos_clientes_id RESTART;
ALTER SEQUENCE seq_datos_obras_sociales_id RESTART;
ALTER SEQUENCE seq_datos_vendedores_vendedor_id RESTART;
ALTER SEQUENCE seq_tmp_mensajeria_anmat_reproceso_mensajeria_id RESTART;
ALTER SEQUENCE seq_datos_condiciones_venta_id RESTART;
ALTER SEQUENCE seq_datos_pacientes_id RESTART;
ALTER SEQUENCE seq_dato_transaccion_transaccion_id RESTART;
ALTER SEQUENCE seq_transacciones_pendientes_anmat_id_transac RESTART;
ALTER SEQUENCE seq_datos_condicion_venta_id RESTART;
ALTER SEQUENCE seq_datos_productos_anexto_producto_id RESTART;
ALTER SEQUENCE seq_detalle_movimientos_detalle_id RESTART;
ALTER SEQUENCE seq_trazabilidad_codigos_codigo_id RESTART;
ALTER SEQUENCE seq_datos_distribuidores_distribuidor_id RESTART;
ALTER SEQUENCE seq_datos_productos_id RESTART;
ALTER SEQUENCE seq_detalle_transacciones_transaccion_detalle_id   RESTART;
ALTER SEQUENCE seq_datos_estanterias_id RESTART;
ALTER SEQUENCE seq_datos_proveedor_id RESTART;
ALTER SEQUENCE seq_emails_email_id             RESTART;                   
ALTER SEQUENCE seq_datos_legra_griega_id RESTART;
ALTER SEQUENCE seq_datos_remesa_remesa_id RESTART;
ALTER SEQUENCE seq_error_transaccion_error_id     RESTART;
ALTER SEQUENCE seq_datos_factura_nro RESTART;
ALTER SEQUENCE seq_orden_cobro_nro RESTART;
ALTER SEQUENCE seq_datos_factura_id RESTART;
ALTER SEQUENCE seq_datos_cobros_id RESTART;
ALTER SEQUENCE seq_cta_cte_id restart;
ALTER SEQUENCE seq_listas_precios_id RESTART;
ALTER SEQUENCE seq_datos_hojas_hoja_id RESTART;
ALTER TABLE datos_listas_precios ALTER lista_padre_id DROP NOT NULL
DELETE FROM tipos_familia_productos
ALTER SEQUENCE seq_tipo_familia_producto_id RESTART


DELETE FROM datos_movimientos;
DELETE FROM detalle_movimientos;
DELETE FROM stock_completo;
DELETE FROM movimientos_trazabilidad;
DELETE FROM datos_lotes;
DELETE FROM datos_facturas;
DELETE FROM detalle_facturas;
DELETE FROM datos_clientes;
DELETE FROM datos_proveedores;
DELETE FROM datos_productos;
DELETE FROM datos_categorias;
DELETE FROM datos_marcas;
DELETE FROM datos_listas_precios;
DELETE FROM datos_vendedores;
DELETE FROM datos_estados;
DELETE FROM datos_hojas_de_ruta;
DELETE FROM detalle_hojas_de_ruta;
DELETE FROM cta_cte_clientes;
DELETE FROM usuarios_secciones WHERE usuario_id >2;
DELETE FROM usuarios_subsecciones WHERE usuario_id >2;
DELETE FROM usuarios_botonera WHERE usuario_id>2;


DROP TABLE lista_precios_1;
DROP TABLE lista_precios_2;
DROP TABLE lista_precios_3;
DROP TABLE lista_precios_4;
DROP TABLE lista_precios_5;
DROP TABLE lista_precios_6;
DROP TABLE lista_precios_7;
DROP TABLE lista_precios_8;
DROP TABLE lista_precios_9;
DROP TABLE lista_precios_10;
DROP TABLE lista_precios_11;
DROP TABLE lista_precios_12;
DROP TABLE lista_precios_13;
DROP TABLE lista_precios_14;
DROP TABLE lista_precios_15;
DROP TABLE lista_precios_16;
DROP TABLE lista_precios_17;
DROP TABLE lista_precios_18;
DROP TABLE lista_precios_19;
DROP TABLE lista_precios_20;
DROP TABLE lista_precios_21;
DROP TABLE lista_precios_22;
DROP TABLE lista_precios_23;
DROP TABLE lista_precios_24;
DROP TABLE lista_precios_25;
DROP TABLE lista_precios_26;
DROP TABLE lista_precios_27;
DROP TABLE lista_precios_28;
DROP TABLE lista_precios_29;
DROP TABLE lista_precios_30;
DROP TABLE lista_precios_31;
DROP TABLE lista_precios_32;
DROP TABLE lista_precios_33;
DROP TABLE lista_precios_34;
DROP TABLE lista_precios_35;
DROP TABLE lista_precios_36;
DROP TABLE lista_precios_37;
DROP TABLE lista_precios_38;
DROP TABLE lista_precios_39;
DROP TABLE lista_precios_40;
DROP TABLE lista_precios_41;
DROP TABLE lista_precios_42;
DROP TABLE lista_precios_43;
DROP TABLE lista_precios_44;
DROP TABLE lista_precios_45;
DROP TABLE lista_precios_46;
DROP TABLE lista_precios_47;
DROP TABLE lista_precios_48;
DROP TABLE lista_precios_49;
DROP TABLE lista_precios_50;
DROP TABLE lista_precios_51;
DROP TABLE lista_precios_52;
DROP TABLE lista_precios_53;
DROP TABLE lista_precios_54;
DROP TABLE lista_precios_55;
DROP TABLE lista_precios_56;
DROP TABLE lista_precios_57;
DROP TABLE lista_precios_58;
DROP TABLE lista_precios_59;
DROP TABLE lista_precios_60;
DROP TABLE lista_precios_61;
DROP TABLE lista_precios_62;
DROP TABLE lista_precios_63;
DROP TABLE lista_precios_64;
DROP TABLE lista_precios_65;
DROP TABLE lista_precios_66;
DROP TABLE lista_precios_67;
DROP TABLE lista_precios_68;
DROP TABLE lista_precios_69;
DROP TABLE lista_precios_70;
DROP TABLE lista_precios_71;
DROP TABLE lista_precios_72;
DROP TABLE lista_precios_73;
DROP TABLE lista_precios_74;
DROP TABLE lista_precios_75;
DROP TABLE lista_precios_76;
DROP TABLE lista_precios_77;
DROP TABLE lista_precios_78;
DROP TABLE lista_precios_79;
DROP TABLE lista_precios_80;
DROP TABLE lista_precios_81;
DROP TABLE lista_precios_82;
DROP TABLE lista_precios_83;
DROP TABLE lista_precios_84;
DROP TABLE lista_precios_85;
DROP TABLE lista_precios_86;
DROP TABLE lista_precios_87;
DROP TABLE lista_precios_88;
DROP TABLE lista_precios_89;
DROP TABLE lista_precios_90;
DROP TABLE lista_precios_91;
DROP TABLE lista_precios_92;
DROP TABLE lista_precios_93;
DROP TABLE lista_precios_94;
DROP TABLE lista_precios_95;
DROP TABLE lista_precios_96;
DROP TABLE lista_precios_97;
DROP TABLE lista_precios_98;
DROP TABLE lista_precios_99;
DROP TABLE lista_precios_100;
DROP TABLE lista_precios_101;
DROP TABLE lista_precios_102;
DROP TABLE lista_precios_103;
DROP TABLE lista_precios_104;
DROP TABLE lista_precios_105;
DROP TABLE lista_precios_106;
DROP TABLE lista_precios_107;
DROP TABLE lista_precios_108;
DROP TABLE lista_precios_109;
DROP TABLE lista_precios_110;
DROP TABLE lista_precios_111;
DROP TABLE lista_precios_112;
DROP TABLE lista_precios_113;
DROP TABLE lista_precios_114;
DROP TABLE lista_precios_115;
DROP TABLE lista_precios_116;
DROP TABLE lista_precios_117;
DROP TABLE lista_precios_118;
DROP TABLE lista_precios_119;
DROP TABLE lista_precios_120;
DROP TABLE lista_precios_121;
DROP TABLE lista_precios_122;
DROP TABLE lista_precios_123;
DROP TABLE lista_precios_124;
DROP TABLE lista_precios_125;
DROP TABLE lista_precios_126;
DROP TABLE lista_precios_127;
DROP TABLE lista_precios_128;
DROP TABLE lista_precios_129;
DROP TABLE lista_precios_130;
DROP TABLE lista_precios_131;
DROP TABLE lista_precios_132;
DROP TABLE lista_precios_133;
DROP TABLE lista_precios_134;
DROP TABLE lista_precios_135;
DROP TABLE lista_precios_136;
DROP TABLE lista_precios_137;
DROP TABLE lista_precios_138;
DROP TABLE lista_precios_139;
DROP TABLE lista_precios_140;
DROP TABLE lista_precios_141;
DROP TABLE lista_precios_142;
DROP TABLE lista_precios_143;
DROP TABLE lista_precios_144;
DROP TABLE lista_precios_145;
DROP TABLE lista_precios_146;
DROP TABLE lista_precios_147;
DROP TABLE lista_precios_148;
DROP TABLE lista_precios_149;
DROP TABLE lista_precios_150;
DROP TABLE lista_precios_151;
DROP TABLE lista_precios_152;
DROP TABLE lista_precios_153;
DROP TABLE lista_precios_154;
DROP TABLE lista_precios_155;
DROP TABLE lista_precios_156;
DROP TABLE lista_precios_157;
DROP TABLE lista_precios_158;
DROP TABLE lista_precios_159;
DROP TABLE lista_precios_160;
DROP TABLE lista_precios_161;
DROP TABLE lista_precios_162;
DROP TABLE lista_precios_163;
DROP TABLE lista_precios_164;
DROP TABLE lista_precios_165;
DROP TABLE lista_precios_166;
DROP TABLE lista_precios_167;
DROP TABLE lista_precios_168;
DROP TABLE lista_precios_169;
DROP TABLE lista_precios_170;
DROP TABLE lista_precios_171;
DROP TABLE lista_precios_172;
DROP TABLE lista_precios_173;
DROP TABLE lista_precios_174;
DROP TABLE lista_precios_175;
DROP TABLE lista_precios_176;
DROP TABLE lista_precios_177;
DROP TABLE lista_precios_178;
DROP TABLE lista_precios_179;
DROP TABLE lista_precios_180;
DROP TABLE lista_precios_181;
DROP TABLE lista_precios_182;
DROP TABLE lista_precios_183;
DROP TABLE lista_precios_184;
DROP TABLE lista_precios_185;
DROP TABLE lista_precios_186;
DROP TABLE lista_precios_187;
DROP TABLE lista_precios_188;
DROP TABLE lista_precios_189;
DROP TABLE lista_precios_190;
DROP TABLE lista_precios_191;
DROP TABLE lista_precios_192;
DROP TABLE lista_precios_193;
DROP TABLE lista_precios_194;
DROP TABLE lista_precios_195;
DROP TABLE lista_precios_196;
DROP TABLE lista_precios_197;
DROP TABLE lista_precios_198;
DROP TABLE lista_precios_199;
DROP TABLE lista_precios_200;
DROP TABLE lista_precios_201;
DROP TABLE lista_precios_202;
DROP TABLE lista_precios_203;
DROP TABLE lista_precios_204;
