[dmelmac]
driver = pgsql
host = localhost
port = 5432
dbname = informacion_limon_local
;schema = db_schema
username = gordon
password = erespandemanteca


[reparto]
driver = pgsql
host = localhost
port = 5432
dbname = informacion_limon_reparto
;schema = db_schema
username = gordon
password = erespandemanteca

