[common]
    ;; CSS que se cargan
    css[] = flix.css
    css[] = generic.css
    css[] = menu.css
    css[] = colorbox.css
    css[] = modal.css
    css[] = jQueryUI.css
    css[] = tooltip.css
    css[] = msgBoxLight.css
    css[] = tooltip.css    

    ;; JS que se cargan
    js[] = jQuery.min-1.8.3.js
    js[] = jQuery.colorbox-min.js
    js[] = jquery-ui.min.js
    ;;js[] = jquery-ui-1.10.3.custom.min.js    
    js[] = flix.js
    js[] = menu.js
    js[] = modal.js
    js[] = jquery.msgBox.js
    js[] = jsCalls.js

;; Valores que envia la primer llamada al process
[defaults_js]
    ;; Valores por default que envia la primer llamada del process
    accion       = hacerBusqueda ; CUIDADO al cambiar este valor!!!!! Requiere ajustar la busqueda de los modales
    ordenarPor   = 
    ordenarOrden = asc
    pagina       = 1
    porPagina    = 10
    tipo         = usuariosSecciones

;; Menu principal y submenues
[menu]
    Movimientos[] = true
    Movimientos[] = Entradas
    Movimientos[] = Salidas
    Movimientos[] = Ingresos
;;    Movimientos[] = Interfaz
;;    Movimientos[] = Agrupadoras

    Laboratorio[] = true
    Laboratorio[] = Autorizaciones
    
    Producción[] = true
    Producción[] = Orden de trabajo
    
    Guias[] = true
    Guias[] = Ordenes
    
    Administración[] = true
    Administración[] = Totales
    Administración[] = Lista de Precios
    Administración[] = Facturas
    Administración[] = Remitos
    Administración[] = Cobros
    Administración[] = Bancos
    Administración[] = Estado de Deuda
    Administración[] = Mayor
    Administración[] = Cheques
    Administración[] = Cuentas
    Administración[] = Relaciones
    Administración[] = Rentabilidad
    Administración[] = Promociones
    Administración[] = Liquidaciones
    Administración[] = Cajas
    Administración[] = Combos
    
    Stock[] = true
    Stock[] = Consulta stock
;;    Stock[] = Stock en custodia
;;    Stock[] = Auditor stock
;;    Stock[] = Control stock
    Stock[] = Stock consolidado
    Stock[] = Asociador stock

    ABMS[] = true
;;    ABMS[] = Sucursales
    ABMS[] = Almacenes
    ABMS[] = Categorias
    ABMS[] = Clientes
;;    ABMS[] = Custodia
;;    ABMS[] = Departamentos
    ABMS[] = Estanterias
    ABMS[] = Estados    
;;    ABMS[] = Laboratorios
    ABMS[] = Localidades
    ABMS[] = Marcas
;;    ABMS[] = Medicos    
;;    ABMS[] = Municipios
;;    ABMS[] = Obras sociales
    ABMS[] = Pacientes    
    ABMS[] = Productos
;;    ABMS[] = Presentaciones
   ABMS[] = Productos Presentaciones
   ABMS[] = Proveedores
;;    ABMS[] = Provincias
    ABMS[] = Vendedores
;;    ABMS[] = Vehiculos
    ABMS[] = Modelos
    ABMS[] = Usuarios
    ABMS[] = Usuarios secciones
    ABMS[] = Usuarios botonera
    ABMS[] = Tipo de Productos
    ABMS[] = Subfamilias
    ABMS[] = Familias subfamilias
    ABMS[] = Codigo de Barra

    Utilidades[] = true
;;    Utilidades[] = Importacion
;;    Utilidades[] = Actualizacion de precios
      Utilidades[] = Etiquetas
    

    Pedidos[] = true
;;    Pedidos[] = Listado de Pendientes
    Pedidos[] = Pedidos
;;    Pedidos[] = Seguimiento Historico
    Pedidos[] = Extranet  

    Distribución[] = true
    Distribución[] = Distribuidores
    Distribución[] = Vehiculos
    Distribución[] = Hoja de ruta
;;    Distribución[] = Seguimiento
    Distribución[] = Seguimiento Historico

;; Se aca hasta el final del archivo
;; Configuraciones propias de cada seccion
[entradas]
    ;; Nombre de la seccion para poner como título
    display_name = Listado de entradas

    ;; Botonera superior de la seccion
    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Alta de stock
    flix_boton_top[] = Devolucion de stock
    flix_boton_top[] = Alta stock por codigo
    flix_boton_top[] = Reimprimir codigo de trazabilidad
    flix_boton_top[] = Exportar entradas

[salidas]
    display_name = Listado de Salidas

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Remito
    flix_boton_top[] = Exportar salidas
    flix_boton_top[] = Preparar pedido
    flix_boton_top[] = Devolucion de stock
    flix_boton_top[] = Roturas
    flix_boton_top[] = Reventa
    flix_boton_top[] = Imprimir
    flix_boton_top[] = Diferencia de precio


[interfaz]
    display_name = Listado de Movimientos Pendientes

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Preparar Movimiento

[agrupadoras]
    display_name = Listado de Trazas Agrupadoras

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Agrupar Desagrupar

[autorizaciones]
    display_name = Listado de Autorizaciones de lotes

     flix_boton_top[] = Busqueda avanzada
;;    flix_boton_top[] = Crear orden
;;    flix_boton_top[] = Exportar salidas
;;    flix_boton_top[] = Preparar orden

    
    
[ordenDeTrabajo]
    display_name = Listado de ordenes de trabajo

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear orden
;;    flix_boton_top[] = Exportar salidas
    flix_boton_top[] = Preparar orden
    
[consultaStock]
    display_name = Consultas de stock

    flix_boton_top[] = Busqueda Avanzada
    flix_boton_top[] = Exportar Stock
flix_boton_top[] = Exportar Consumo

    ;; Campo usado para ordenar por default
    defaultOrder = Nombre
[stockEnCustodia]
    display_name = Productos en custodia

    flix_boton_top[] = Busqueda Avanzada
    ;; Campo usado para ordenar por default
    defaultOrder = Nombre
    
[auditorStock]
    display_name = Auditor de stock

    flix_boton_top[] = Busqueda Avanzada
;;    flix_boton_top[] = Exportar Auditor

[controlStock]
    display_name = Control de stock

    flix_boton_top[] = Control

[clientes]
    display_name = Listado de clientes

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo
    flix_boton_top[] = Exportar

[categorias]
    display_name = Listado de categorias

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo

[productos]
    display_name = Listado de productos

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo
    flix_boton_top[] = Exportar productos
    flix_boton_top[] = Actualizar comision
[presentaciones]
    display_name = Listado de Presentaciones

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo

[productos-presentaciones]
    display_name = Relacion de productos y presentaciones

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo
    
[marcas]
    display_name = Listado de marcas

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo

[medicos]
    display_name = Listado de medicos

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo

[pacientes]
    display_name = Listado de pacientes

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo

[proveedores]
    display_name = Listado de proveedores

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo

[almacenes]
    display_name = Listado de almacenes

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo

[estanterias]
    display_name = Listado de estanterias

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo

[sucursales]
    display_name = Listado de sucursales

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo

[obrasSociales]
    display_name = Listado de obras sociales

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo

[vendedores]
    flix_boton_top[] = Busqueda avanzada    
    flix_boton_top[] = Crear nuevo
[laboratorio]
    flix_boton_top[] = Busqueda avanzada    
    flix_boton_top[] = Crear nuevo
[laboratorios]
    flix_boton_top[] = Busqueda avanzada    
    flix_boton_top[] = Crear nuevo

[municipios]
    flix_boton_top[] = Busqueda avanzada    
    flix_boton_top[] = Crear nuevo

[departamentos]
    flix_boton_top[] = Busqueda avanzada    
    flix_boton_top[] = Crear nuevo

[distribuidores]
    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo

[vehiculos]
    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo   
[importacion]
    display_name = Importador

    flix_boton_top[] = Importador

[busquedaPorCodigo]
    display_name = Busqueda por codigo

[transacciones]
    display_name = Transacciones
    flix_boton_top[] = Busqueda avanzada

[bloqueador]
    display_name = Bloqueador
    flix_boton_top[] = Busqueda avanzada

[transaccionesAgrupadas]
    display_name = Transacciones agrupadas
    flix_boton_top[] = Busqueda avanzada
;;    flix_boton_top[] = Exportador movimientos SAP

[pendientesDeConfirmacion]
    display_name = Transacciones Pendientes de Recepción
    flix_boton_top[] = Busqueda avanzada
	
[listadoDePendientes]
    display_name = Listado de pendientes
    flix_boton_top[] = Busqueda avanzada

[estados]
    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo

[pedidos]
    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Alta pedidos

[provincias]
    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo

[localidades]
    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo
    
[vehiculos]
    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo

[hojaDeRuta]
    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Alta HDR
    flix_boton_top[] = Actualizar HDR

[seguimiento]
    flix_boton_top[] = Busqueda avanzada

[seguimientoHistorico]
    flix_boton_top[] = Busqueda avanzada

[custodia]
    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo
[actualizacionDePrecios]
    display_name = Listado de cotizacion del dolar
    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Actualizar
[producción]
    display_name = Producción
    flix_boton_top[] = Busqueda avanzada
[mensajeria]
    display_name = Mensajeria
    flix_boton_top[] = Busqueda avanzada
[modelos]
    display_name = Modelos
    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo
[usuarios]
    display_name = Usuarios
    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo  
[usuariosSecciones]
    display_name = Usuarios secciones
    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Alta de seccion subseccion
[usuariosBotonera]
    display_name = Usuarios botonera
    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Alta de botones
[ingresos]
    display_name = Ingresos
    flix_boton_top[] = Busqueda avanzada
[extranet]
    display_name = Extranet
    flix_boton_top[] = Busqueda avanzada
[listaDePrecios]
    display_name = Lista de Precios

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo   
    flix_boton_top[] = Actualizar productos
    flix_boton_top[] = Actualizar subfamilias  
    flix_boton_top[] = Exportar listas 
[remitos]
    display_name = Listado de remitos
    flix_boton_top[] = Busqueda avanzada
[facturas]
    display_name = Listado de remitos

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo
[cobros]
    display_name = Listado de cobros

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo
    flix_boton_top[] = Nota de credito
    flix_boton_top[] = Devolucion de caja
    flix_boton_top[] = Rendir caja
[cajas]
    display_name = Listado de cajas

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Rendir caja

[bancos]
    display_name = Listado de Bancos

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo
[estadoDeDeuda]
    display_name = Estado de deuda

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Exportar listado
    flix_boton_top[] = Exportar
[mayor]
    display_name = Listado de mayor

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Exportar mayor
    flix_boton_top[] = Crear nuevo
    flix_boton_top[] = Exportar
[cheques]
    display_name = Listado de mayor

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Imputar
    flix_boton_top[] = Exportar cheques
[cuentas]
    display_name = Listado de Cuentas

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo
[relaciones]
    display_name = Listado de Clientes->Cuentas

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo
[tipoDeProductos]
    display_name = Tipo de Productos
    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo
[ordenes]
    display_name = Ordenes de guias
    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo
[totales]
    display_name = Total stock y deuda
    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo
[rentabilidad]
    display_name = Rentabilidad

    flix_boton_top[] = Busqueda Avanzada
    flix_boton_top[] = Exportar Rentabilidad
[subfamilias]
    display_name = Subfamilias
    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo
[familiasSubfamilias]
    display_name = Relacion familias->subfamilias
    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo
[promociones]
    display_name = Listado de promociones

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo
[liquidaciones]
    display_name = Listado de liquidaciones

    flix_boton_top[] = Busqueda avanzada
    flix_boton_top[] = Crear nuevo
[etiquetas]
    display_name = Etiquetas
    flix_boton_top[] = Imprimir
[codigoDeBarra]
    display_name = Codigo de Barra
    flix_boton_top[] = Busqueda Avanzada
[stockConsolidado]
    display_name = Stock Consolidado
    flix_boton_top[] = Busqueda Avanzada
[productosPresentaciones]
    display_name = Productos Presentaciones
    flix_boton_top[] = Busqueda Avanzada
    flix_boton_top[] = Crear nuevo
[combos]
    display_name = Combos
    flix_boton_top[] = Busqueda Avanzada
    flix_boton_top[] = Crear nuevo
[asociadorStock]
    display_name = Asociador stock
    flix_boton_top[] = Busqueda Avanzada
